In [1]:
import numpy as np

***Numpy indexing & Slicing of vectors***

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6] #index

np.int64(17)

In [4]:
#slicing
arr[1:6]

array([12, 13, 14, 15, 16])

In [5]:
arr[:6] #by default it takes 0{as initial index}

array([11, 12, 13, 14, 15, 16])

In [6]:
arr[:] #by default: 0th initial index - last final index

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
#steps slicing
arr[4::2]

array([15, 17, 19])

***Numpy indexing & Slicing of Matrix***

In [8]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[3] #rows indexing {starting from 0}

array([16, 17, 18, 19, 20])

In [10]:
arr[3,4] #i'th row j'th column

np.int64(20)

In [11]:
slice_arr = arr[3:, 3:]
slice_arr

array([[19, 20],
       [24, 25],
       [29, 30]])

In [12]:
arr[:, 4] #column indexing {starting from 0} -> now this a vector

array([ 5, 10, 15, 20, 25, 30])

***Boolean indexing***

In [13]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
bool_index = (arr%2 == 0)
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [15]:
bool_arr = arr[bool_index]
bool_arr

array([12, 14, 16, 18, 20])