In [1]:
import numpy as np

***Arithmetic Operation***

In [2]:
a1 = np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [3]:
a2 = np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [4]:
sum = a1 + a2 #{size must be same}
sum

array([ 7,  9, 11, 13, 15])

In [5]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2 #a1^(a2)

array([      1,     128,    6561,  262144, 9765625])

***Broadcasting***

In [10]:
l = [10,20,30,40]
arr = np.array(l)

In [11]:
arr + 10

array([20, 30, 40, 50])

In [12]:
arr2 = np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

***Deep & Shallow copy***

In [14]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice_arr = a[:5]
slice_arr *=10
slice_arr

array([10, 20, 30, 40, 50])

In [16]:
a #slice{shallow copy of a} -> no changes occur in 'a'

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
b = a

In [18]:
b[0] = 77 #now a changes -> deep copy
a

array([77, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
#copy
b = a.copy()
b[0] = 7

In [20]:
b

array([ 7, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a

array([77, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

***Matrix Operation***

In [22]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [23]:
B = np.array([[5,6], [7,8]])
B

array([[5, 6],
       [7, 8]])

In [24]:
#Matrix multiplication:
A @ B

array([[19, 22],
       [43, 50]])

In [25]:
#also:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
#Transpose
A.T

array([[1, 3],
       [2, 4]])

***Advance Array Manipulation***

*Stacking Array:*

In [28]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [29]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [30]:
#vertical stack
np.vstack((a,b)) #{length of vectors/arrays should be same}

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
#horizontal stack
np.hstack((a,b)) #{join}

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
#column stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting Array:*

In [33]:
s = np.arange(16).reshape(4,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.hsplit(s,2) #s{array}, 2{horizontal splits}

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
np.vsplit(s,2) #s{array}, 2{vertically splits}

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]