In [587]:
import numpy as np

***Valid Sudoku***

In [588]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [589]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [590]:
np.sum(s,axis=1) #sum of all rows individually

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [591]:
np.sum(s, axis=0) #sum of all columns individually

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [592]:
#extracted the 1st block of Sudoku
s[:3, :3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [593]:
#extracted the 2nd block of Sudoku
s[:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [594]:
#extracted the 3rd block of Sudoku
s[:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

Optimized solution:

In [595]:
for i in range(0,9, 3):
    for j in range(0,9, 3):
        b = s[i:i+3, j:j+3]
        # print(b)
        print(b.sum())

45
45
45
45
45
45
45
45
45


***General ques***

In [596]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [597]:
#Get the shape of the matrix
data.shape

(5, 3)

In [598]:
#Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [599]:
#Extract Math marks of all students
data[:, 1]

array([85, 92, 76, 65, 90])

In [600]:
#Find the highest Science mark
data[:, 2].max()

np.int64(95)

In [601]:
#Get details of the student who scored more than 90 in Math
x = data[:, 1] > 90
data[x]

array([[19, 92, 88]])

In [602]:
#Increase Math marks of all students by 5
data[:, 1] + 5

array([90, 97, 81, 70, 95])

In [603]:
#Find how many students are younger than 19.
y = data[:, 0] < 19
younger = data[y]
print(f"younger students data: \n {younger}")

younger students data: 
 [[18 85 78]
 [17 76 95]
 [18 65 70]]


In [604]:
print(f"{len(data[y])} students are younger than 19")

3 students are younger than 19


In [605]:
#Calculate the average marks in each subject (column-wise mean)
maths = data[:, 1:2]
maths

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [606]:
maths.mean()

np.float64(81.6)

In [607]:
sci = data[:, 2:]
sci

array([[78],
       [88],
       [95],
       [70],
       [85]])

In [608]:
sci.mean()

np.float64(83.2)

In [609]:
#compact version of average marks for maths, sci.
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [610]:
#Get data of students who scored at least 80 in both subjects
m = data[:, 1] >= 80
s = data[:, 2] >=80
data[m & s]

array([[19, 92, 88],
       [20, 90, 85]])

In [611]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [612]:
#Replace all Science marks < 75 with 0.
target = data[:, 2] < 75
data[:,2][target] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])